### ISSUE TITLE
Errors! errors! errors!!!

### ISSUE THREAD

**Issue by AidenWard13** [segonzal/pyVoxel#1]
So yeah... I keep having a problem with the shader script...

---

finished reading image
finished updating chunk (0, 16, 0)

Traceback (most recent call last):
  File "C:\Users\Aiden\Desktop\pyVoxel-master\main.py", line 109, in <module>
    main()
  File "C:\Users\Aiden\Desktop\pyVoxel-master\main.py", line 104, in main
    view.update()
  File "C:\Users\Aiden\Desktop\pyVoxel-master\View.py", line 54, in update
    self.model.render(self.shader)
  File "C:\Users\Aiden\Desktop\pyVoxel-master\SuperChunk.py", line 59, in render
    self.chunks[n].render(shader)
  File "C:\Users\Aiden\Desktop\pyVoxel-master\Chunk.py", line 204, in render
##     glVertexAttribPointer(p_loc, 3, GL_FLOAT, False, stride, ctypes.c_void_p(offset))

So all i would like is to know the version of python you wrote this on.
If you could give me links to the versions, that'd be great! xD

Thanks.

**Comment by segonzal** [comment]
The reason I dropped this project was that I could not select the OGL version I wanted.
Every time I tested it on a different computer I had to make changes. I don't actually remember with wich version this code worked. If I recall correctly it's GLSL 330 and OGL 4.x.

I re-used the shader class later, and had to make several changes for it to work on an older version of OGL and GLSL.
You should only had to change the shaders, and maybe the render method of Chunk.py

**Comment by AidenWard13** [comment]
Thanks for the reply! (Even though it would have been nice 2 months ago xD)
But that information was useful to know!
Plus, it quite ok anyway... I were making my own in Python, which i started around about 4 month ago...
And got up to a point where i had nice terrain loading in chunks, i had the Minecraft steve skin which i gave all the animation to when crouching, walking, rotating your head... I had swimming, and runnings... But that was near the early stages, and i didn't know of all the speed ups. I just threw tons of stuff together, regardless of how slow it were going to be... Once the chunks all loaded, you could play it fine without any lag... Anyway, besides that, i also didn't design the world nice to look at... Since then i implemented the shade for the sides of the blocks... And the ambient occlusion effect that builds up around the corner of faces depending on the adjacent blocks...

I implemented the minecraft style lighting system in 2D, but didn't bother adding it to my minecraft yet... And really, i was spending so much time figuring out all the things i need to speed generating a chunk region up....

I re-made the engine so you call a function to gen a chunk, it'll ensure the surrounding chunks exist, so later we can check all the exposed faces. (otherwise generating the next chunk would require regenerating the one's we already have...) and generating a further outer layer, cause when populating chunks with trees, they could spread from the outer bound, in to the loaded chunks, and in the further opposite bounds...

Besides that, there were a simple queue loading each chunk in 16x16x16 segments...
Only if there were anything in them segments to generate... And if after checking those exposed faces, if there were any...

Cause obviously if it's entirely filled with air, or is underground and entirely filled with stone and other solid blocks, it's not exposed...

So all that work i had going on... In minecraft, i'm sure, based on what i've seen from playing the game, that they use the player's frustum in order to decide which chunks to generate, so they don't waste time with all the things that a deep down that you can't see anyway, and the ton of stuff behind you, which the stuff infront of you is more required at start...

I didn't do any of that... (i were going to, just didn't yet)

so i had terrain loading chunks, but i guess even with as fast as a pure python set of simple rules is, it's just not as fast as other languages...

Having just played Minecraft on PC which is in Java, and seeing how fast they can load all the chunks... And knowing that in Python, multithreading isn't actually possible... due to the Global Interpreter Lock... It's just quite sad...

And thinking of a time when i would want to implement monsters... Having all the processing for them done, you know, like all the path finding... That would really lag in Python, and so i never would get to implement them...

So recently... Yep... I've decided...
I'm gonna do it in Java...

I've been all over the internet recently checking out a major ton of tutorials...
I downloaded eclipse, since that's what Notch used...

And i also have the LWJGL (Lightweight Java Game Library) implemented and got VAO's rendering what i want in OpenGL...

I did implement VAO's in my Python minecraft also... To speed up the rendering... At best i could render about 5 million quads at around 30-40 fps... In python...

Anyway... I've written you way too much that i should have...
I have a YouTube channel, (not the most popular, 344 subscribers), and i uploaded some of my Python Minecraft work there...

Oh yeah, i also forgot to mention, i implemented the Minecraft menu also... :)
I were also working on day/night cycle... For rendering the sun and moon... Didn't get around to doing stars... Think minecraft generates them in it's code, rather than using a texture.

Anyway, i guess this old video would show you what the terrain was like.
https://www.youtube.com/watch?v=NWbovKqaO8M&t=188s

Ok, c-ya! :]
